### ISSUE TITLE
Keep getting "No Players"

### ISSUE THREAD

**Issue by rvaworm** [PsiLupan/MakeLobbiesGreatAgain#110]
I keep getting "No Players" as survivor or as killer In Dead By Daylight. I uninstalled and reinstalled and rebooted many times but no success. I ran the debug command and this is what I got: 
c:\Users\****\Desktop\MLGA>java -jar MLGA.jar
Up to date!
Java Version: 1.8.0_181
12:10:10.847 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.99-r7, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.99-r7, based on libpcap version 1.8.1
0
0
0
12:10:11.536 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet, use default value: 2
12:10:11.536 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet6, use default value: 23
12:10:11.536 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.packet, use default value: 17
12:10:11.536 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.link, use default value: 18
0
0
0
0
0
0
1
12:10:11.549 [main] INFO org.pcap4j.core.Pcaps - 10 NIF(s) found.
Found: 1 - Realtek PCIe GBE Family Controller #2 ::: 192.168.1.2
Found: 2 - Realtek PCIe GBE Family Controller #2 ::: 192.168.1.2
Using IP from textfield: 192.168.1.2
0
0
0
0
0
0
0
0
0
1
12:10:26.183 [main] INFO org.pcap4j.core.Pcaps - 10 NIF(s) found.
12:10:26.188 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.dlt.raw, use default value: 12
java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(Unknown Source)
        at mlga.io.peer.PeerReader.<init>(PeerReader.java:26)
        at mlga.io.peer.PeerTracker.<init>(PeerTracker.java:33)
        at mlga.ui.Overlay.<init>(Overlay.java:45)
        at mlga.Boot.main(Boot.java:80)
No Peers file located! Checking backups!
java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(Unknown Source)
        at mlga.io.peer.PeerReader.<init>(PeerReader.java:26)
        at mlga.io.peer.PeerTracker.<init>(PeerTracker.java:33)
        at mlga.ui.Overlay.<init>(Overlay.java:45)
        at mlga.Boot.main(Boot.java:80)

**Comment by SeraphimShovel88** [comment]
I'm getting this too
