### ISSUE TITLE
"No Players"

### ISSUE THREAD

**Issue by fadedace123** [PsiLupan/MakeLobbiesGreatAgain#114]
I've tried everything i can think of but no matter what i do it just says "no players" whenever the game is on. debug info below

C:\Users\Josh\Desktop\mlga>java -jar MLGA.jar
Up to date!
Java Version: 1.8.0_201
07:59:31.941 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.991, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.991, based on libpcap version 1.8.1
Save file has not been created yet. Skipping loading.
07:59:32.477 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet, use default value: 2
07:59:32.478 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet6, use default value: 23
07:59:32.478 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.packet, use default value: 17
07:59:32.478 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.link, use default value: 18
0
0
0
0
0
0
0
0
1
07:59:32.495 [main] INFO org.pcap4j.core.Pcaps - 9 NIF(s) found.
Found: 1 - Intel(R) Dual Band Wireless-AC 7265 ::: 192.168.1.5
Using device from dropdown: 1 - Intel(R) Dual Band Wireless-AC 7265 ::: 192.168.1.5
0
0
0
0
0
0
0
0
1
07:59:38.875 [main] INFO org.pcap4j.core.Pcaps - 9 NIF(s) found.
07:59:38.878 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.dlt.raw, use default value: 12
java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(Unknown Source)
        at mlga.io.peer.PeerReader.<init>(PeerReader.java:26)
        at mlga.io.peer.PeerTracker.<init>(PeerTracker.java:33)
        at mlga.ui.Overlay.<init>(Overlay.java:45)
        at mlga.Boot.main(Boot.java:80)
No Peers file located! Checking backups!
java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(Unknown Source)
        at mlga.io.peer.PeerReader.<init>(PeerReader.java:26)
        at mlga.io.peer.PeerTracker.<init>(PeerTracker.java:33)
        at mlga.ui.Overlay.<init>(Overlay.java:45)
        at mlga.Boot.main(Boot.java:80)

**Comment by SeraphimShovel88** [comment]
this is exactly what i have!!!

**Comment by fadedace123** [comment]
yeah there's a few other reports about it that dont have any solutions, im hoping that a current bug report might get more attention

**Comment by edemauro** [comment]
+1. Same issue.

**Comment by fadedace123** [comment]
Okay so I had given up on MLGA working for me for a while but tonight decided to try again, I did multiple things and I'm not sure which part fixed MLGA for me, so first ill list everything i did that didnt work and then what i did when it did work. First i read edemauro's comment and created an MLGA folder in %appdata% and then i moved the MLGA.jar file into that folder and tried running mlga multiple times. sometimes before launching dbd, sometimes after launching dbd, neither worked. So from there I uninstalled npcap and checked if mlga was working then, it wasnt. So i went and watched an mlga install tutorial, https://www.youtube.com/watch?v=XWINGDvbSfM. In that install tutorial i was told to download the mlga.zip and unzip the contents, and then double click MLGA.iml. It told me i had no program to run MLGA.iml, and finally i redownloaded the MLGA.jar file and moved it into the unzipped folder that was created when i unzipped MLGA.zip, and from there I launched dbd, and then double clicked MLGA.jar and it's working.

For a final note, this may be useless to others since it has to do with my systems, but the when mlga is selected a network device to use mlga would only give me one option in the dropdown menu, when that one option was listed as intel-(bunch of stuff i cant remember)-(My IPv4 Adress) it didnt work, but now the network setting in the dropdown menu says Realtek PCIe GBE Family Controller ::: (An IPV4 address that had the last digit changed since the last time i tried using mlga)

I'm sure all i've typed is very confusing and not well explained but hopefully it can help someone else
