### ISSUE TITLE
No devices found. Try running in admin mode.

### ISSUE THREAD

**Issue by TemperrS** [PsiLupan/MakeLobbiesGreatAgain#22]
I'm running it as admin but its not working, when i try typing my ip it says "The device you selected doesn't seem to exist. Double-check the IP you entered".

Version 1.26 :: Up to date!
Java Version: 1.8.0_131
15:04:55.476 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.86, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.86, based on libpcap version 1.8.1
15:04:56.372 [main] INFO org.pcap4j.core.Pcaps - No NIF was found.

**Comment by PsiLupan** [comment]
Uninstall NPCap, reboot, then reinstall. I had a similar issue during initial testing of Npcap.

**Comment by Xhaviour92** [comment]
got same error, solution dont helped at all

**Comment by TemperrS** [comment]
After try typing the ip in 1.3 it shows that 

18:42:04.104 [main] INFO org.pcap4j.core.Pcaps - No NIF was found.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
        at mlga.Boot.main(Boot.java:68)
        ... 5 more

**Comment by AzukiMPGH** [comment]
Uninstall npcap and install winpcap
that worked for me
