### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native

### ISSUE THREAD

**Issue by zero2dash** [PsiLupan/MakeLobbiesGreatAgain#23]
I've tried
- WinPCap
- NPCap
- Creating .bat file and running as Admin
- Windows 7 Pro (64-bit)
- Java installed is current, Version 8, Update 131 (64-bit)

Using newest version of MLGA (1.26).

Here's the contents of the Command window:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>d:

D:\>java -jar mlga.jar
Version 1.26 :: Up to date!
Java Version: 1.8.0_131
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain static m
ethod fromNative(Method, Object) from class com.sun.jna.Native
        at com.sun.jna.Native.initIDs(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:148)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
        at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:48)
        at org.pcap4j.core.Pcaps.libVersion(Pcaps.java:464)
        at mlga.Sanity.checkPCap(Sanity.java:57)
        at mlga.Sanity.check(Sanity.java:22)
        at mlga.Boot.main(Boot.java:49)

D:\>

Let me know if you'd like me to try anything, or if you need any additional information from me.

**Comment by PsiLupan** [comment]
That looks like an issue with the library. It's throwing an error when it tries to find the NPcap/WinPcap installation.

**Comment by PsiLupan** [comment]
I've updated the JNA library, which was throwing the error. Mind retesting?

**Comment by zero2dash** [comment]
Sure, absolutely, I'd be happy to test again and help out.
