### ISSUE TITLE
MLGA No players

### ISSUE THREAD

**Issue by Luna1001** [PsiLupan/MakeLobbiesGreatAgain#76]
My MLGA says theres no players but I am in a game anyone know how to fix this

**Comment by alui07** [comment]
Try restarting MLGA and ensuring that the IP address is correct because that can change

**Comment by Luna1001** [comment]
I have had that when mlga wont dtart and i changed my ip back and mlga starts then it says no players even in swf where i had all my friends as loved it says no players

**Comment by Luna1001** [comment]
Wont start*

**Comment by alui07** [comment]
Do you manually type it out, or do you use the IP address dropdown menu?

**Comment by Luna1001** [comment]
I type it out

**Comment by alui07** [comment]
try using the dropdown

**Comment by back3r** [comment]
ping shows for a few seconds, then no players and then this pops up
> Exception in thread "main" java.lang.IllegalArgumentException: length is zero.
        at org.pcap4j.util.ByteArrays.validateBounds(ByteArrays.java:1061)
        at org.pcap4j.packet.UnknownDnsRData.newInstance(UnknownDnsRData.java:39)
        at org.pcap4j.packet.factory.StaticDnsRDataFactory.newInstance(StaticDnsRDataFactory.java:322)
        at org.pcap4j.packet.factory.StaticDnsRDataFactory.newInstance(StaticDnsRDataFactory.java:317)
        at org.pcap4j.packet.factory.StaticDnsRDataFactory.newInstance(StaticDnsRDataFactory.java:40)
        at org.pcap4j.packet.DnsResourceRecord.<init>(DnsResourceRecord.java:135)
        at org.pcap4j.packet.DnsResourceRecord.newInstance(DnsResourceRecord.java:78)
        at org.pcap4j.packet.DnsPacket$DnsHeader.<init>(DnsPacket.java:521)
        at org.pcap4j.packet.DnsPacket$DnsHeader.<init>(DnsPacket.java:355)
        at org.pcap4j.packet.DnsPacket.<init>(DnsPacket.java:56)
        at org.pcap4j.packet.DnsPacket.newPacket(DnsPacket.java:52)
        at org.pcap4j.packet.factory.StaticUdpPortPacketFactory$4.newInstance(StaticUdpPortPacketFactory.java:75)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:46)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:23)
        at org.pcap4j.packet.UdpPacket.<init>(UdpPacket.java:83)
        at org.pcap4j.packet.UdpPacket.newPacket(UdpPacket.java:53)
        at org.pcap4j.packet.factory.StaticIpNumberPacketFactory$1.newInstance(StaticIpNumberPacketFactory.java:41)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:46)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:23)
        at org.pcap4j.packet.IpV4Packet.<init>(IpV4Packet.java:94)
        at org.pcap4j.packet.IpV4Packet.newPacket(IpV4Packet.java:61)
        at org.pcap4j.packet.factory.StaticEtherTypePacketFactory$1.newInstance(StaticEtherTypePacketFactory.java:37)
        at org.pcap4j.packet.factory.StaticEtherTypePacketFactory.newInstance(StaticEtherTypePacketFactory.java:111)
        at org.pcap4j.packet.factory.StaticEtherTypePacketFactory.newInstance(StaticEtherTypePacketFactory.java:24)
        at org.pcap4j.packet.EthernetPacket.<init>(EthernetPacket.java:102)
        at org.pcap4j.packet.EthernetPacket.newPacket(EthernetPacket.java:61)
        at org.pcap4j.packet.factory.StaticDataLinkTypePacketFactory$1.newInstance(StaticDataLinkTypePacketFactory.java:39)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:46)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:23)
        at org.pcap4j.core.PcapHandle.getNextPacket(PcapHandle.java:648)
        at mlga.Boot.main(Boot.java:89)
