### ISSUE TITLE
1.39 incompatible JNA native library installed

### ISSUE THREAD

**Issue by Orgoth** [PsiLupan/MakeLobbiesGreatAgain#79]
I hope you can help me.
If you need more Information, let me know.
I tried to find a solution but google wasn't very helpful.

System: Windows 10 Pro 1703 Build 15063.483 64Bit

```java -jar G:\Downloads\mlga\MLGA.jar
Java Version: 1.8.0_131
java.lang.Error:

There is an incompatible JNA native library installed on this system
Expected: 5.1.0
Found:    4.0.1
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the
   jnidispatch library included with the JNA jar file you are using

        at com.sun.jna.Native.<clinit>(Native.java:199)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
        at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:47)
        at org.pcap4j.core.Pcaps.libVersion(Pcaps.java:464)
        at mlga.Sanity.checkPCap(Sanity.java:54)
        at mlga.Sanity.check(Sanity.java:20)
        at mlga.Boot.main(Boot.java:61)
You MUST have NPCap or WinPCap installed to allow this program to monitor the lobby!
An installer link will attempt to open.```

**Comment by Orgoth** [comment]
I have installed the lastest Version of JAVA SE Development Kit and it works now.
