### ISSUE TITLE
Ping for a few seconds then no players with log

### ISSUE THREAD

**Issue by back3r** [PsiLupan/MakeLobbiesGreatAgain#86]
Shows ping for a few seconds and makes a back up of profile then i get this.
Tried npcap, win10pcap and winpcap. I've reinstalled java, I recently did a reformat not just for this app but same issue on both. 
Windows 10 64 bit

Exception in thread "main" java.lang.IllegalArgumentException: length is zero.
        at org.pcap4j.util.ByteArrays.validateBounds(ByteArrays.java:1061)
        at org.pcap4j.packet.UnknownDnsRData.newInstance(UnknownDnsRData.java:39)
        at org.pcap4j.packet.factory.StaticDnsRDataFactory.newInstance(StaticDnsRDataFactory.java:322)
        at org.pcap4j.packet.factory.StaticDnsRDataFactory.newInstance(StaticDnsRDataFactory.java:317)
        at org.pcap4j.packet.factory.StaticDnsRDataFactory.newInstance(StaticDnsRDataFactory.java:40)
        at org.pcap4j.packet.DnsResourceRecord.<init>(DnsResourceRecord.java:135)
        at org.pcap4j.packet.DnsResourceRecord.newInstance(DnsResourceRecord.java:78)
        at org.pcap4j.packet.DnsPacket$DnsHeader.<init>(DnsPacket.java:521)
        at org.pcap4j.packet.DnsPacket$DnsHeader.<init>(DnsPacket.java:355)
        at org.pcap4j.packet.DnsPacket.<init>(DnsPacket.java:56)
        at org.pcap4j.packet.DnsPacket.newPacket(DnsPacket.java:52)
        at org.pcap4j.packet.factory.StaticUdpPortPacketFactory$4.newInstance(StaticUdpPortPacketFactory.java:75)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:46)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:23)
        at org.pcap4j.packet.UdpPacket.<init>(UdpPacket.java:83)
        at org.pcap4j.packet.UdpPacket.newPacket(UdpPacket.java:53)
        at org.pcap4j.packet.factory.StaticIpNumberPacketFactory$1.newInstance(StaticIpNumberPacketFactory.java:41)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:46)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:23)
        at org.pcap4j.packet.IpV4Packet.<init>(IpV4Packet.java:94)
        at org.pcap4j.packet.IpV4Packet.newPacket(IpV4Packet.java:61)
        at org.pcap4j.packet.factory.StaticEtherTypePacketFactory$1.newInstance(StaticEtherTypePacketFactory.java:37)
        at org.pcap4j.packet.factory.StaticEtherTypePacketFactory.newInstance(StaticEtherTypePacketFactory.java:111)
        at org.pcap4j.packet.factory.StaticEtherTypePacketFactory.newInstance(StaticEtherTypePacketFactory.java:24)
        at org.pcap4j.packet.EthernetPacket.<init>(EthernetPacket.java:102)
        at org.pcap4j.packet.EthernetPacket.newPacket(EthernetPacket.java:61)
        at org.pcap4j.packet.factory.StaticDataLinkTypePacketFactory$1.newInstance(StaticDataLinkTypePacketFactory.java:39)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:46)
        at org.pcap4j.packet.factory.AbstractStaticPacketFactory.newInstance(AbstractStaticPacketFactory.java:23)
        at org.pcap4j.core.PcapHandle.getNextPacket(PcapHandle.java:648)
        at mlga.Boot.main(Boot.java:89)

**Comment by Frubi22** [comment]
same here

**Comment by PsiLupan** [comment]
Let me know if the new 1.40 fixes it. pcap4j had some bug fixes in the newer version.
