### ISSUE TITLE
Error. Unable to locate devices.

### ISSUE THREAD

**Issue by kuromi** [PsiLupan/MakeLobbiesGreatAgain#97]
debug log is here.
```
E:\Downloads\mlga>java -jar MLGA.jar
java.lang.NumberFormatException: For input string: "BUP"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at mlga.ui.GithubPanel.parseReleases(GithubPanel.java:210)
        at mlga.ui.GithubPanel.<init>(GithubPanel.java:56)
        at mlga.Sanity.checkUpdate(Sanity.java:73)
        at mlga.Sanity.check(Sanity.java:20)
        at mlga.Boot.main(Boot.java:61)
Version: 1.4
Java Version: 1.8.0_151
13:49:05.462 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.96, based on libpcap version 1.8.1
Pcap Info: Npcap version 0.96, based on libpcap version 1.8.1
13:49:05.622 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet, use default value: 2
13:49:05.623 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet6, use default value: 23
13:49:05.623 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.packet, use default value: 17
13:49:05.623 [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.link, use default value: 18
13:49:05.642 [main] INFO org.pcap4j.core.Pcaps - 7 NIF(s) found.
```

WinPcap 4.1.3 also same error.
What should i do?

Thanks.

**Comment by Tom-Dane** [comment]
file-run cmd-run cmd as administrator-do the same thing

**Comment by Josemaloco** [comment]
Is that the full log?

It looks ok, but after that last line it should also read: 
"... [main] INFO org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.dlt.raw, use default value: 12"
, and a few more.

**Comment by kuromi** [comment]
Yes, it is full log.
I dont know what is wrong.

**Comment by Josemaloco** [comment]
Is the MLGA icon still in the notification area after launch?

Also, in your mlga.settings.ini, whats the value of "addr"?

**Comment by kuromi** [comment]
yes. If I dont close the error dialog box..
But, MLGA does not display "no player".

and mlga.settings.ini is Just one line of "autoload=0"

**Comment by Josemaloco** [comment]
Nvm, when I read your title I though of something else. The problem is that it can´t find any valid internal addresses. 

Wait for the developer to answer, as he might already know how this happens. I assume you already tried in admin mode?

**Comment by kuromi** [comment]
Sure. I tried the administrator mode by batch.

I will wait for the developer's answer.
thanks for your responce!
